### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by not-an-aardvark** [prettier/eslint-plugin-prettier#105]
I haven't used this plugin myself for awhile. It seems like it's been useful to a lot of people, which is great, but it could use an active maintainer who also uses the plugin and has enough time to give issues/PRs the attention that they need.

As open-source projects go, this project is fairly low-activity (11 issues/PRs in the last month) and I think it's mostly feature-complete. There are a few outstanding issues like (https://github.com/prettier/eslint-plugin-prettier/issues/65 and https://github.com/prettier/eslint-plugin-prettier/issues/81) that should probably be solved at some point.

**Comment by paliwalgaurav** [comment]
Interested

**Comment by BPScott** [comment]
Hi @not-an-aardvark, I'm using eslint-plugin-prettier at work on a day-to-day basis and I maintain [stylelint-prettier](https://github.com/bpscott/stylelint-prettier), which does basically the same thing but hooking into stylelint instead of eslint so I've got a bit of context around using the prettier API.

I'd be interested in helping out maintaining the project. I'd also be interested in moving stylelint-prettier into the prettier organization but I think that's a question for another prettier org member.

Other potential future work:
* Drop node 4 support (prettier v1.13 and eslint v5.0 both require node 6)
* Remove pragma support as it is now supported natively by prettier. (#54)
* Extracting utilities that can be shared across multiple prettier integrations into a new library (#101)

**Comment by not-an-aardvark** [comment]
@BPScott Just sent you an invite!
