### ISSUE TITLE
Destructuring_assignment error Insert `;`

### ISSUE THREAD

**Issue by u007** [prettier/eslint-plugin-prettier#115]
**What version of `eslint` are you using?**

5.6.1
**What version of `prettier` are you using?**

1.14.3

**What version of `eslint-plugin-prettier` are you using?**

2.6.2

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

.prettierrc

```
{
  "semi": false,
  "singleQuote": true
}
```

.eslintrc

```
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    'plugin:vue/recommended',
    'plugin:prettier/recommended'
  ],
  // required to lint *.vue files
  plugins: [
    'vue',
    'prettier'
  ],
  // add your custom rules here
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  }
}

```

**What source code are you linting?**
```
[, x, y, scale] = [1,2,3,4]
```

**What did you expect to happen?**
expect no error thrown

**What actually happened?**

```
error Insert `;`
```

**Comment by j-f1** [comment]
This is an [intentional behavior](https://prettier.io/docs/en/rationale.html#semicolons):

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtANAAgB5YJ5YDOYAhgDZwC6mAvJqgIxYBMWAzFgCyUjogQAHGAEtohZKBIAnKRADuABWkJxKEgDcIwgCa8QAIykkwAazgwAygOPCoAc2QwpAVzh9bhOFJgKjdgLYkyABm5J58AFaE2ABCRqbmFiT+cAAytnAhYW4g1lKeUsgGJPp4ZNB6AlK2MADqOjAAFsgAHAAMfFUQnrVGAkVVcAXqmXxScACOzsLjviQBQUihZOEgnv7CWSs5hLZ2FACKzhDwW6swJfXaTcisIE4kwmR7AMIQ-oFFUNCjIM6eABUSqplp4AL5goA)
```sh
--parser babylon
--no-semi
```

**Input:**
```jsx
[, x, y, scale] = [1, 2, 3, 4]
```

**Output:**
```jsx
;[, x, y, scale] = [1, 2, 3, 4]

```
