### ISSUE TITLE
Prettier not running when I run through webpack eslint-loader

### ISSUE THREAD

**Issue by rafaellages-hotmart** [prettier/eslint-plugin-prettier#117]
Hello, Ive successfully configured eslint-plugin-prettier in my project files when I run it through command line. It works great.
But when Im bring up my local dev env with webpack, It runs eslint-loader module that automatically fix my files on save. But since Id configure eslint-plugin-prettier on my eslint, it simple don't run prettier.
Digging in eslint-loader code, I found that it uses eslint's executeOnText method.
Isn't eslint-plugin-prettier called when you run eslint from executeOnText?

**Versions:**
"eslint": "^5.6.1",
"prettier": "^1.14.3",
"eslint-plugin-prettier": "^3.0.0",
"eslint-config-prettier": "^3.1.0",

My .eslintrc file:
`
{
  "root": true,
  "env": {
    "node": true,
    "browser": true
  },
  "extends": [
    "plugin:vue/recommended",
    "plugin:prettier/recommended",
    "airbnb-base"
  ],
  "parserOptions": {
    "parser": "babel-eslint",
    "ecmaVersion": 2017,
    "sourceType": "module"
  }
}
`

**What did you expect to happen?**
I expect it to run prettier together with eslint fix. As it does when I run it through command line

**What actually happened?**
It only run eslint fix

**Comment by BPScott** [comment]
> Isn't eslint-plugin-prettier called when you run eslint from executeOnText?

We hook into Eslint's standard extension points in the documented way. I would be very surprised if one of ESLint's execution APIs did not trigger plugins registered using their plugin APIs.

Is it just the fix functionality that does not work or is any prettier error reporting not being shown? I note that [eslint-loader 2.1.1 has broken autofixing for some people](https://github.com/webpack-contrib/eslint-loader/issues/248)

Given that everything works as expected when you run `eslint` from the command line I suspect eslint-loader is the root cause of your issue rather than eslint-plugin-prettier.

---

eslint-plugin-prettier makes prettier infer the file type that is being parsed based upon the file extension of the file provided. Recent versions of prettier do nothing with file extensions it does not understand. It may be that eslint-loader does not pass through that file extension as you would expect.

In your node_modules folder can you add a `console.log(prettierOptions)` right above [this line where we pass options into prettier](https://github.com/prettier/eslint-plugin-prettier/blob/68271f8a8fc0e219716b08d1a9ba759fc068839a/eslint-plugin-prettier.js#L212) and show me the value when (a) you run eslint from the command line and everything works as expected and (b) when you run eslint via eslint-loader. I would be interested to see if there are any differences between these environments, and it may help identify how eslint-loader is behaving differently to running from the command line.

**Comment by rafaellages-hotmart** [comment]
Hi thanks to helping me to debug it.
By digging deep in the point in code you gave me I could see that it run as expected, it just didn't run in the file that I was testing it was ignored by a wrong glob pattern, so it was my fault 😳
Sorry, and thanks again for the help.
