### ISSUE TITLE
Only lint <script> portion of .vue file?

### ISSUE THREAD

**Issue by syropian** [prettier/eslint-plugin-prettier#132]
Is it possible to only have prettier run on the `<script>` portion of a `.vue` file? Prettier's rules seem to conflict with `plugin:vue/recommended` so fixing one often breaks the other (in the template context). 

--- 

**What version of `eslint` are you using?**: `^5.9.0`

**What version of `prettier` are you using?**: `^1.15.3`

**What version of `eslint-plugin-prettier` are you using?**: `^3.0.0`

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```js
module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 2018
  },
  extends: ['prettier', 'plugin:vue/recommended'],
  plugins: ['prettier', 'vue'],
  rules: {
    'prettier/prettier': 'error',
  },
  overrides: [
    {
      files: ['**/*.test.js'],
      env: {
        jest: true
      }
    }
  ]
}

```

**What source code are you linting?**: `.vue` file

**Comment by BPScott** [comment]
This plugin does not have any concept of the code that is provided to it, it doesn't do any kind of parsing so isn't able to extract out parts that you don't want.

If you want to avoid conflicts between prettier and eslint-plugin-vue, then then [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) contains [a config that shall disable the vue plugins rules that conflict with prettier styling](https://github.com/prettier/eslint-config-prettier/blob/master/vue.js). It also has some opinions on the configuration of [vue/html-self-closing](https://github.com/prettier/eslint-config-prettier#vuehtml-self-closing) so that its configuration does not conflict with prettier's output should you wish to continue using that.

I also note that their docs state that you should put "prettier" at the end of your extends array so that it overrides other configuration.

Modify your  .eslintrc like so:

```
extends: ['plugin:vue/recommended', 'prettier', 'prettier/vue'],
```

**Comment by syropian** [comment]
I do want to avoid conflicts between them, but I want `eslint-plugin-vue` to be the canonical when it comes to a collision, and I think your proposed solution does the opposite. I suppose I could always just revert to an older version of Prettier...

**Comment by BPScott** [comment]
If you want to customize the output that prettier provides, then you probably want to use [prettier-eslint](https://github.com/prettier/prettier-eslint#the-problem) to run prettier then eslint over your files instead of using this plugin to run prettier within eslint.

If prettier formats things in a way that conflicts with vue's recommendations and you believe that prettier's output should change then I suggest raising issues within [prettier/prettier](https://github.com/prettier/prettier) repo.

**Comment by syropian** [comment]
@BPScott It looks like the folks handling eslint-plugin-vue are already on the case! https://github.com/vuejs/eslint-plugin-vue/pull/698

With that I'm happy to close this issue. Thanks for all your help! 🙌
