### ISSUE TITLE
eslint-config-prettier is used but not listed in peerDependencies or devDependencies

### ISSUE THREAD

**Issue by kirill-konshin** [prettier/eslint-plugin-prettier#143]
**What version of `eslint-plugin-prettier` are you using?**

3.0.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

```json
{
  "extends": [
    "eslint:recommended",
    "plugin:prettier/recommended"
  ],
}
```

**What did you expect to happen?**

When I install `eslint-plugin-prettier` I expect that `eslint-config-prettier` referenced in recommended settings will be installed automatically (or at least will appear in `peerDependencies`).

**What actually happened?**

I have to manually install `eslint-config-prettier`.

**Comment by BPScott** [comment]
Please see https://github.com/prettier/eslint-plugin-prettier/pull/128#issuecomment-440494343 for reasons why `eslint-config-prettier` is not included as a peer dependency.

The [readme](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration] states you must install eslint-config-prettier separately.

**Comment by kirill-konshin** [comment]
This explanation does not make much sense TBH. If you *must* install something then it is a peer dependency. If a package refers another package (even under condition) - it is a peer. If you don’t want it to be listed as peer then don’t refer it, simply remove the recommended config. Otherwise it leads to completely unexpected error.

**Comment by not-an-aardvark** [comment]
There are some downsides to our current approach -- ESLint usually loads shareable configs relative to the config that extends them, so it would attempt to resolve `eslint-config-prettier` from the location of `eslint-plugin-prettier` rather than from the user's project. As a result, under some package management setups (e.g. Yarn Plug n' Play) ESLint could fail to find the `eslint-config-prettier` package even though the user installed it in their project.

A solution would be to add `eslint-plugin-prettier` as a dependency rather than as a `peerDependency`; this would avoid the need for the user to manually install it, although it would still add unnecessary installation time in some cases. The user would no longer be able to customize the version of `eslint-config-prettier` that gets used through this plugin, although if they want customization they could just install their own version of `eslint-plugin-prettier`.
