### ISSUE TITLE
html attributes format by max-line-length

### ISSUE THREAD

**Issue by cybermerlin** [prettier/eslint-plugin-prettier#346]
guys, how can I disable this rule-fixer?
![image](https://user-images.githubusercontent.com/1460479/95743210-0bf47880-0c9a-11eb-81c2-754a7c65b866.png)

I want to stay in my style for this case.

---------------

**What version of `eslint` are you using?**

**What version of `prettier` are you using?**

**What version of `eslint-plugin-prettier` are you using?**

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

**What source code are you linting?**

**What did you expect to happen?**

**What actually happened?**

**Comment by BPScott** [comment]
You can't opt out of Prettier's rules at a global level, this is because of it ethos that [configuration will lead to more depating over styles, and the whole point of prettier is to stop those debates](https://prettier.io/docs/en/option-philosophy.html). \

If you want to opt out of prettier's formatting in a single case then you can use [`prettier-ignore` comments](https://prettier.io/docs/en/ignore.html)
