### ISSUE TITLE
Eslint padded blocks rule ignored by eslint-prettier

### ISSUE THREAD

**Issue by jacquesdev** [prettier/eslint-plugin-prettier#350]
I hope this is the right place to post this issue. The main issue I am having is that I have an eslint rule in place that enforces padded-blocks in classes, ie a blank newline at the start and end of my class. The prettier error that I get however, is that I need to delete the newline. I cannot find an option to add to eslint prettier to prevent this from happening. I saw some mention of setting  `endOfLine: 'auto',` but this did not make a difference. Any help appreciated.

**What version of `eslint` are you using?**
6.5.1

**What version of `prettier` are you using?**
2.1.2

**What version of `eslint-plugin-prettier` are you using?**
3.1.4

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

.prettierrc.js
```
module.exports = {
  singleQuote: true,
  trailingComma: 'es5',
  parser: 'flow',
  semi: false,
}
```

.eslintrc.js
```
rules: {
    'comma-dangle': [2, 'only-multiline'],
    semi: [2, 'never'],
    'max-len': [2, 80, 2, { ignorePattern: '^import.*from.*$|t\\(.*\\)$' }],
    'max-nested-callbacks': [2, 5],
    yoda: 0,
    'padded-blocks': ['error', { 'classes': 'always' }],
    'space-before-function-paren': [2, 'never'],
    'no-console': 2,
    'prefer-promise-reject-errors': 0,
    'promise/catch-or-return': 'error',
    'react/display-name': 0,
    'no-shadow': 0,
    'prettier/prettier': ['error', {
      'arrowParens': 'avoid',
    }],
  },
```

**What source code are you linting?**

```
class Foo extends React.Component<Props> {

  render() {
    return <Text>Hello World</Test>
  }

}
```

**What did you expect to happen?**
I expect the rule 'padded-blocks': ['error', { 'classes': 'always' }], to be taken into account by prettier, to not get an error at the new lines at the start and end of the class.

**What actually happened?**
I get the error `Delete `⏎`eslintprettier/prettier` on the padded block new lines in the class

**Comment by BPScott** [comment]
You shouldn't enable eslint rules that conflict with prettier. This is because prettier's ethos is that [prettier should handle code formatting, while linters should handle code quality](https://prettier.io/docs/en/comparison.html).

You should disable that rule. You can use https://github.com/prettier/eslint-config-prettier to disable all rules that would conflict with prettier. That package also provides a helper tool that lets you identify any rules that you currently have enabled that would conflict with prettier's styling.
