### ISSUE TITLE
[Bug] Prettier can't cope with 'object-property-newline': 'error'

### ISSUE THREAD

**Issue by wenfangdu** [prettier/eslint-plugin-prettier#400]
**What version of `eslint` are you using?**
`6.8.0`
**What version of `prettier` are you using?**
`1.19.1`
**What version of `eslint-plugin-prettier` are you using?**
`3.3.1`
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

`.prettierrc`

None

`.eslintrc`

```js
{
  "rules": {
    "object-property-newline": "error"
  }
}
```

**What source code are you linting?**

```js
const foo = { foo: 'foo', bar: 'bar' }
```

**What did you expect to happen?**

```js
const foo = {
  foo: 'foo',
  bar: 'bar',
}
```

**What actually happened?**

```js
const foo = { foo: 'foo', bar: 'bar' }
```

**Comment by lydell** [comment]
Hi!

The `object-property-newline` rule fixes the code into this:

```js
var foo = { foo: 'foo',
bar: 'bar' }
```

However, since there’s no line break between the `{` and `foo`, Prettier will join it up on one line again (the object is short enough to fit on one line). That’s how Prettier works – see https://prettier.io/docs/en/rationale.html#multi-line-objects and https://github.com/prettier/prettier/pull/5205

So unfortunately you have to fix this manually.

I’m closing this since there’s no action eslint-plugin-prettier (this repo) can take here.

(Note: Next time, please post an ESLint config that actually works to save people’s time 🙏 )
