### ISSUE TITLE
"error  Delete `⏎`  prettier/prettier" in .vue files

### ISSUE THREAD

**Issue by pieterwouda** [prettier/eslint-plugin-prettier#42]
I get a _"Delete `⏎`  prettier/prettier"_ error within the script tags of my **.vue** files.

![Delete `⏎`  prettier/prettier](https://i.imgur.com/QjTULzz.png "Delete `⏎`  prettier/prettier")

I'm using VS Code with ESLint.
When I save the **.vue** file, it auto-'fixes' the file using prettier, only not in the preferred way.

![Fixed: Delete `⏎`  prettier/prettier](https://i.imgur.com/bSKuYuI.png "Fixed: Delete `⏎`  prettier/prettier")

There might be something wrong with my **.eslintrc.json** file, but I'm not sure what it is.

**.eslintrc.json**
```javascript
{
  "root": true,
  "parser": "babel-eslint",
  "env": {
    "browser": true
  },
  "extends": [
    "standard",
    "eslint:recommended",
    "prettier"
  ],
  "plugins": [
    "html",
    "prettier"
  ],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true
      }
    ]
  }
}
```

**.babelrc**
```javascript
{
  "presets": [
    "env",
    "stage-2"
  ]
}
```

**.vscode/settings.json**
```javascript
{
  "eslint.autoFixOnSave": true,
  "eslint.validate": [
    "javascript",
    {
      "language": "vue",
      "autoFix": true
    }
  ]
}
```

**Comment by not-an-aardvark** [comment]
Thanks for reporting. Does this issue also occur when you use `prettier` directly?

**Comment by pieterwouda** [comment]
I'm not sure how to use `prettier` directly on a **.vue** file.

When I run `prettier "src/views/Test.vue"`, I get the another error.

> SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (7:1)

![](https://i.imgur.com/6aZep4i.png)

**Comment by not-an-aardvark** [comment]
This seems like it might be an issue with the html parser you're using (possibly `eslint-plugin-html`).

`eslint-plugin-prettier` works as part of a larger stack:

1. ESLint reads a file
1.  A preprocessor preprocesses the `.vue` source text into JavaScript text
1. `babel-eslint` parses the JavaScript text into an AST
1. `eslint` runs `eslint-plugin-prettier` and gives it the AST and the text
1. `eslint-plugin-prettier` runs `prettier` on the text, and reports problems to `eslint` based on a diff with `prettier`'s output
1. `eslint` reports the problems

I'm not quite sure where the issue is occurring here, but I'm think it's in step 2. I'm fairly certain it's not an issue with `eslint-plugin-prettier` itself, because it just takes the text that ESLint gives it and passes it to `prettier`.

**Comment by BenoitZugmeyer** [comment]
For those interested, it will be fixed in `eslint-plugin-html` https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/76

🥂

**Comment by wahengchang** [comment]
it is still existed, there is not way to fix the error `38:2  error  Delete `⏎`  prettier/prettier`

**Comment by CharlesKumar** [comment]
Hi @wahengchang 
you can fix that error by running the command
`npx prettier --write "src/**/*.vue"`

check whether there are any pending errors by using the command
`npx prettier --check "src/**/*.vue"`

see [here](https://prettier.io/docs/en/cli.html) for more details

NOTE: you can install prettier globally with `npm i -g prettier` and be sure to use the version you need. (usually the latest version)

**Comment by AlexBrohshtut** [comment]
Another fix that worked for me is to switch default html formatter to 'prettier' (it was prettyhtml for some reason):
![image](https://user-images.githubusercontent.com/966690/62803888-5c9b9f00-baf4-11e9-906f-a5bd8f785883.png)

**Comment by PVautour** [comment]
I fixed it by changing my .editorconfig to use tabs instead of spaces. here is an example file:

change _indent_style = space_ to _indent_style = tab_


# editorconfig.org
root = true

[*]
indent_style = tab
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

**Comment by gldraphael** [comment]
Possibly related if everyone having this issue is on Windows:

The project `npm run build`s without errors on a Mac, but throws the following on a Windows CI machine:

> warning  Delete `␍`                    prettier/prettier

![image](https://user-images.githubusercontent.com/10794213/72904178-7b18ee00-3d54-11ea-9f28-a1ee931dfdc9.png)

The fix (in my case) was to make sure line-endings for `.vue` files aren't changed by git on checkout, by adding the following to `.gitattributes`:

```
* text=auto
*.vue text eol=lf
```

(If it doesn't work, do try re-cloning after pushing changes to the `.gitattributes` file.)

((You could also set `end_of_line = lf` in your `.editorconfig` if you use VS Code's editorconfig plugin but that'll only fix it for editorconfig users.))
