### ISSUE TITLE
Trouble with comment write.

### ISSUE THREAD

**Issue by zotille** [prettier/eslint-plugin-prettier#423]
**What version of `eslint` are you using?**
7.25.0

**What version of `prettier` are you using?**
2.0.4
**What version of `eslint-plugin-prettier` are you using?**
^3.3.1

I think it should allow me write comment this way:
![image](https://user-images.githubusercontent.com/38178024/127843619-32070f1f-9af8-460a-88d7-f046bc93a15e.png)

but it gave an error, and make my comment always in one line. 😭

**Comment by BPScott** [comment]
Prettier doesn't like trailing whitespace at the end of a line. [This playground](N4Igxg9gdgLgprEAuEB6AVOgOlABO3AZwgFs5dISzZdad9cYALASygHND71UQAaEBAAOMFtELJQAQwBOMiAHcACrIQSUUgDYKpATwkCARjKlgA1nBgBlIabbtkMGQFc4AuCUNwAJt58AZKQ5nKXY4ADEIGRIpGFEOZBApZxgIfhAmGBJNAHVWeEJbMDgrNRZRADdy3USwQgMQNkI4GRglE3YY5AAzLWaBACtCAA8AIRNzSyspMn82OB6) suggests that prettier is totally fine with placing comments across multiple lines once you remove that trailing whitespace.

If something else is changing the linebreaks then it sounds like some other eslint rule might be breaking you.

You shouldn't enable eslint rules that conflict with prettier. This is because prettier's ethos is that [prettier should handle code formatting, while linters should handle code quality](https://prettier.io/docs/en/comparison.html).

You should disable that rule. You can use https://github.com/prettier/eslint-config-prettier to disable all rules that would conflict with prettier. That package also provides a helper tool that lets you identify any rules that you currently have enabled that would conflict with prettier's styling.
