### ISSUE TITLE
The confict for `'@typescript-eslint/comma-dangle'`

### ISSUE THREAD

**Issue by tianyingchun** [prettier/eslint-plugin-prettier#459]
**What version of `eslint` are you using?**
eslint@8.11.0,   "typescript": "^4.6.2"
**What version of `prettier` are you using?**
^2.6.0
**What version of `eslint-plugin-prettier` are you using?**
^4.0.0
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
{
  "singleQuote": true,
  "trailingComma": "all",
  "tabWidth": 2,
  "printWidth": 110,
  "endOfLine": "auto"
}

**What source code are you linting?**
```
export function Model<MT extends ModelType, ExtContext,>(models: MT, extContext?: ExtContext): API<MT>;
export function Model<M extends Models,>(models: M, initialState?: TypeAny): APIs<M>;
export function Model<M extends Models, ExtContext,>(
  models: M,
  initialState?: TypeAny,
  extContext?: ExtContext,
): APIs<M>;
```

**What did you expect to happen?**

<img width="826" alt="image" src="https://user-images.githubusercontent.com/2833251/158583061-87d6e383-5663-46c9-a2f6-c318fe7aea10.png">

the typescript `generic comma` can be allow 

**What actually happened?**

<img width="920" alt="image" src="https://user-images.githubusercontent.com/2833251/158583181-05a67e05-2e7c-4d7f-b49f-ca178827f58f.png">

**Comment by BPScott** [comment]
You shouldn't enable eslint rules that conflict with prettier. This is because prettier's ethos is that [prettier should handle code formatting, while linters should handle code quality](https://prettier.io/docs/en/comparison.html).

You should disable that rule. You can use https://github.com/prettier/eslint-config-prettier to disable all rules that would conflict with prettier. That package also provides a helper tool that lets you identify any rules that you currently have enabled that would conflict with prettier's styling.


I note that eslint-config-prettier added `@typescriot-eslint/comma-dangle` to its list rules to be disabled in [version 6.1.2 (released September 2020)](https://github.com/prettier/eslint-config-prettier/blob/3dfe8c6301897260486e13bc22712e824958c422/CHANGELOG.md#version-6120-2020-09-25)
