### ISSUE TITLE
docs: improve why `usePrettierrc` option is needed

### ISSUE THREAD

**Issue by JounQin** [prettier/eslint-plugin-prettier#506]
@BPScott I don't quite understand why we add `usePrettierrc` option in #83, `prettierrc` is used for all tools, it should always be preferred, I have no idea about in which case we should have inconsistent prettier settings, what do you think?

Maybe @eliperelman @azz @not-an-aardvark can help me to understand?

_Originally posted by @JounQin in https://github.com/prettier/eslint-plugin-prettier/issues/481#issuecomment-1173593965_

**Comment by BPScott** [comment]
#83 was before my time. It is possible to run prettier without loading the prettierrc config file [via the CLI's --no-config option](https://prettier.io/docs/en/cli.html#--no-config) or through the API by [calling `prettier.format()` without passing through the options generated by calling `resolveConfig`](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options).

I suspect #83 was added to maintain parity with those options, because somebody was creating some tool that wrapped over prettier/eslint with a set of hardcoded, unconfigurable settings. 

I agree that 99% of the time users should won't need this functionality, and that they should rely on settings their options in their .prettierrc file. However somebody clearly had a need for it and the maintenance overhead is negligible, so I think it is worthwhile to keep this setting.

**Comment by JounQin** [comment]
I want to understand in which case a user would want a different config between ESLint and prettier itself.

**Comment by JounQin** [comment]
close via #510
