### ISSUE TITLE
npm install --save-dev eslint-plugin-prettier fails to install when using node 18

### ISSUE THREAD

**Issue by krishollenbeck** [prettier/eslint-plugin-prettier#583]
**What version of `eslint` are you using?**
"eslint": "^7.20.0",

**What version of `prettier` are you using?**
"prettier": "3.0.3",

**What version of `eslint-plugin-prettier` are you using?**
None, Issue is with installation

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
N/A

**What source code are you linting?**
N/A

**What did you expect to happen?**
`npm install --save-dev eslint-plugin-prettier` Should install without error.

**What actually happened?**
`npm install --save-dev eslint-plugin-prettier` throws an error when using node 18
ERESOLVE unable to resolve dependency tree

<img width="873" alt="image" src="https://github.com/prettier/eslint-plugin-prettier/assets/1056684/99552437-e381-4f8f-b64b-808698982241">

I can work around it by using `--force or --legacy-peer-deps` but this doesn't appear to be recommended.

**Comment by BPScott** [comment]
`eslint-plugin-prettier` v5.0.0 dropped support for eslint v7.x, it only works with eslint 8.0 and above, as stated in our peerDependencies and that's why npm is saying "your packages don't match the requested peer dependencies".

You need to update your version of eslint from v7 to v8. I note that eslint v8 was [released 2 years ago](https://www.npmjs.com/package/eslint?activeTab=versions).
