### ISSUE TITLE
eslintPluginOptions should not be used/inherited

### ISSUE THREAD

**Issue by niftylettuce** [prettier/eslint-plugin-prettier#62]
You're inheriting defaults which is not obvious to the users using this package

https://github.com/prettier/eslint-plugin-prettier/blob/master/eslint-plugin-prettier.js#L362

That should only be set if and only if "fb" is used.  Otherwise you're inheriting defaults which are not the normal defaults Prettier uses, and is super confusing to end users.

**Comment by not-an-aardvark** [comment]
I am confused about what the issue is here. It seems like configuration is pulled from the following sources:

* A `.prettierrc` config file
* The options passed to the rule

Both of these options are passed in by the user, so I don't see what "defaults" you're referring to. Could you clarify what the problem is (preferably by describing an example configuration where `eslint-plugin-prettier` behaves unexpectedly)?

**Comment by niftylettuce** [comment]
Yes ignore issue, sorry see #60
