### ISSUE TITLE
autoFixOnSave alternates between correct and wrong indentation 

### ISSUE THREAD

**Issue by dj-hedgehog** [prettier/eslint-plugin-prettier#69]
**What version of `eslint` are you using?** 4.11.0
**What version of `prettier` are you using?** 1.8.2
**What version of `eslint-plugin-prettier` are you using?** 2.3.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

Global settings VSCode:

```
  "eslint.autoFixOnSave": true,
```

.eslintrc.json

```
{
  "extends": "prettier",
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2017
  },
  "env": {
    "es6": true,
    "node": true
  },
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "semi": false,
        "printWidth": 120
      }
    ]
  }
}
```

I have quite strange error. I set `eslint.autoFixOnSave` to `true`. When I save a file once it formats my code successfully:

![image](https://user-images.githubusercontent.com/7140800/33176185-7836f5fc-d05e-11e7-802b-083591a901c4.png)

When I save it again it messes up the indentation.

![image](https://user-images.githubusercontent.com/7140800/33176226-9d8798ca-d05e-11e7-864b-ba160f684dca.png)

When I save a 3rd time it fixes the indentation again as in screenshot 1 and so on.

How can this happen?
This is my `.eslintrc.json`:

```
{
  "extends": "prettier",
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2017
  },
  "env": {
    "es6": true,
    "node": true
  },
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "semi": false,
        "printWidth": 120
      }
    ]
  }
}
```

*Edit:* I recorded a video with the strange behaviour:

![eslint-problem](https://user-images.githubusercontent.com/7140800/33177813-43a1a160-d064-11e7-82cb-9656dc78dc7d.gif)

**Comment by not-an-aardvark** [comment]
Hi,

My guess is that the `indent` rule or another code formatter in your editor is somehow being turned on, and it's applying a different fix to your code. I'm a bit confused about why that would be happening, because it doesn't seem like you have the `indent` rule configured, and based on your video there are no problems visible in one of the cases. My recommendation would be to double-check your editor configuration to make sure nothing else is making changes to your files, or if you don't find anything you could report an issue with your editor integration.

I'm going to close this since I don't think it's a problem with `eslint-plugin-prettier`, but feel free to comment if you figure anything out.
